### ISSUE TITLE
Semver support

### ISSUE THREAD

**Issue by stevethomas** [chriskonnertz/open-graph#14]
Hello, have been a happy user of this package for 6 months or so however the latest commits were not backwards compatible. 

Any chance of tagging a release and implementing semver?

**Comment by chriskonnertz** [comment]
Hello, thank you for your feedback.

Release/Tag: https://github.com/chriskonnertz/open-graph/releases/tag/v1.0.0

I will stick to semantiv version from now on.

**Comment by stevethomas** [comment]
thanks much appreciated!
