### ISSUE TITLE
Setting description can generate an invalid string

### ISSUE THREAD

**Issue by oppiansteve** [chriskonnertz/open-graph#17]
Since it uses `substr` rather than `mb_substr` a multibyte character spanning the max length boundary will get turned into an invalid character.

Luckily the fix is trivial, but it would be nice to have a test case added too :-)

**Comment by chriskonnertz** [comment]
I am not sure if this test case is trivial.

Guess the idea is to test a string that causes trouble with the current implementation but will not with the updated, right?

**Comment by oppiansteve** [comment]
Yep, that's right.

**Comment by chriskonnertz** [comment]
https://github.com/chriskonnertz/open-graph/commit/a2ebbd8d9bb33aa657c3f38604b84ba3ca3d9634

**Comment by chriskonnertz** [comment]
Test: https://github.com/chriskonnertz/open-graph/blob/mb_substr/tests/OpenGraphTests.php#L95 (green)

**Comment by chriskonnertz** [comment]
Are you ok with that?

**Comment by oppiansteve** [comment]
Looks good although it should be reading the text back from the opengraph object, of course
