### ISSUE TITLE
Are keywords supported? (no, because OGP does not support it)

### ISSUE THREAD

**Issue by InstanceOfMichael** [chriskonnertz/open-graph#18]
Example:
```
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
```

**Comment by chriskonnertz** [comment]
No, they are not. Only the pure [OGP](http://ogp.me/) stuff.

I wonder why you ask this question? Did you install this package, because you assumed it does support meta tags? (Maybe the Readme is misleading)

**Comment by InstanceOfMichael** [comment]
I installed this library a year ago and then yesterday noticed my OG code didn't have keywords and that the documentation didn't mention keywords. Thank you for clarifying. I was using this in addition to regular SEO and somehow forgot that this OG was not literally SEO.

**Comment by chriskonnertz** [comment]
Okay thank you for this explanation.
