### ISSUE TITLE
REQUEST URI not set

### ISSUE THREAD

**Issue by huglester** [chriskonnertz/open-graph#20]
Hello,

when running tests, from CLI, you can get: that REQUEST URI is unidetified.

At this string:$safeRequestURI = htmlentities(strip_tags(urldecode($_SERVER['REQUEST_URI'])));

is the 'isset()' here enoght? Or are there any other 'cirmustances' to avoid?

Thank you

**Comment by chriskonnertz** [comment]
What do you think about these changes? 

https://github.com/chriskonnertz/open-graph/commit/5f91f49734101c80d367a078fee6bfeb9fbf6515

**Comment by chriskonnertz** [comment]
(PS: I'll add a test.)

**Comment by huglester** [comment]
As far as I understand, laravel uses this variable 'url' => env('APP_URL', 'http://localhost'),
when run from CLI.

maybe we could first try, if there is getenv('APP_URL'), before defaulting to localhost?

**Comment by chriskonnertz** [comment]
Sure why not.

**Comment by chriskonnertz** [comment]
Update: https://github.com/chriskonnertz/open-graph/blob/cli/src/ChrisKonnertz/OpenGraph/OpenGraph.php#L330

**Comment by huglester** [comment]
Seems bood I think

**Comment by chriskonnertz** [comment]
Ok merged the branch. 

https://github.com/chriskonnertz/open-graph/releases/tag/v1.0.3
