### ISSUE TITLE
title not found

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [chriskonnertz/open-graph#23]
it doesn't work in laravel 5.5. Getting this error:

Call to undefined method ChrisKonnertz\OpenGraph\OpenGraphFacade::title()

**Comment by chriskonnertz** [comment]
Hello,

tested it and it works fine.

My `routes/web.php` file looks like this:

```
<?php

/* ... */

Route::get('/', function () {
    $og= OpenGraph::title('test');
});
```

My `composer.json` file looks like this:

```
{
    ...
    "require": {
        "chriskonnertz/open-graph": "^1.0",
        ...
    },
    ...
}
```

And finally my `bootstrap/cache/packages.php` file looks like this:

```
<?php return array (
   'chriskonnertz/open-graph' => 
  array (
    'providers' => 
    array (
      0 => 'ChrisKonnertz\\OpenGraph\\OpenGraphServiceProvider',
    ),
    'aliases' => 
    array (
      'OpenGraph' => 'ChrisKonnertz\\OpenGraph\\OpenGraphFacade',
    ),
  ),
  ...
);
```

**Comment by matthijs-neijenhuijs** [comment]
Weird, my composer.json:

` "chriskonnertz/open-graph": "~1",`

my packages.php:

`  'chriskonnertz/open-graph' => 
  array (
    'providers' => 
    array (
      0 => 'ChrisKonnertz\\OpenGraph\\OpenGraphServiceProvider',
    ),
    'aliases' => 
    array (
      'OpenGraph' => 'ChrisKonnertz\\OpenGraph\\OpenGraphFacade',
    ),
  ),`

**Comment by matthijs-neijenhuijs** [comment]
it seems new OpenGraph(); doesn't work anymore.

**Comment by chriskonnertz** [comment]
Okay, when I test the code of your controller the error occurs here as well.

**Comment by chriskonnertz** [comment]
I think its a mistake in the README.md. Actually when using Laravel 5.5 with auto-discovery of packages
"OpenGraph" is an alias for the facade (`OpenGraphFacade`), not for the `OpenGraph` class.

So basically you have to write your code

```
$og = new OpenGraph();

$og->title('Apple Cookie')
    ->type('article')
    ->image('http://example.org/apple.jpg')
    ->description('Welcome to the best apple cookie recipe never created.')
    ->url();
```

this way:

```

        $og = OpenGraph::title('Apple Cookie')
            ->type('article')
            ->image('http://example.org/apple.jpg')
            ->description('Welcome to the best apple cookie recipe never created.')
            ->url();
```

I will change the README.md or the behaviour.

Thank you for reporting this issue.

**Comment by chriskonnertz** [comment]
Todo: Check if this can be closed.

**Comment by chriskonnertz** [comment]
Wonderful, so now it is time to close this issue.
