### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jenokizm** [chriskonnertz/open-graph#24]
```
$og = new ChrisKonnertz\OpenGraph\OpenGraph();

$og->title('Apple Cookie')
    ->type('article')
    ->image('http://example.org/apple.jpg')
    ->description('Welcome to the best apple cookie recipe never created.')
    ->url();

$res = $og->renderTags();

print_r($res);
echo $res;
var_dump($res); //string(0) ""
```
The result variable is empty. Nothing is output. Why is that?
ps php 7.2

**Comment by chriskonnertz** [comment]
Hello,

I am sorry for not responding earlier. I will test this as soon as possible.

**Comment by chriskonnertz** [comment]
No issue with PHP 7.0.x.

**Comment by chriskonnertz** [comment]
I changed the test of the `renderTags()` methdo a little bit to proof that:
https://github.com/chriskonnertz/open-graph/blob/master/tests/OpenGraphTests.php#L112
The test is green with PHP 7.2.

By the way, you realise that when you print the `$res` value with `echo` into a HTML page, the tags will be interpreted as HTML and therefore are only visible in the source code of the HTML page?

**Comment by jenokizm** [comment]
Yes, I know about it. That's why I did **var_dump()** which showed 0 that means no data

**Comment by chriskonnertz** [comment]
Okay. Any exotic php.ini settings?

**Comment by jenokizm** [comment]
I did not change anything, all for default as indicated in the package https://ospanel.io/.  By the way the best local package I know.

**Comment by chriskonnertz** [comment]
Unfortunately, this is only available in Russian? The last time  I have seen cyrillic letters was in an infamous Counter-Strike 1.6 installer (legal disclaimer: I do not say that I have used it :D ). Can't understand a word...

My problem is that I do not have a PHP 7.2 environment set up. To be honest I bet this is not a general issue of the Open Graph library but a problem of the environment. My argument is that it is running fine on the PHP 7.2 environment of Travis CI: https://travis-ci.org/chriskonnertz/open-graph/jobs/351932933
