### ISSUE TITLE
asset($imageFile) function

### ISSUE THREAD

**Issue by shadowrps** [chriskonnertz/open-graph#28]
By accident i pass wrong image string to `image()` method and get strange error:  
`Call to undefined function ChrisKonnertz\OpenGraph\asset()`

I found several `asset` function calls in `OpenGraph` class:
https://github.com/chriskonnertz/open-graph/blob/d0ddc588383f738146c8f64953c7214fd0fa0214/src/ChrisKonnertz/OpenGraph/OpenGraph.php#L275
https://github.com/chriskonnertz/open-graph/blob/d0ddc588383f738146c8f64953c7214fd0fa0214/src/ChrisKonnertz/OpenGraph/OpenGraph.php#L470

Fast investigation gave me no traces of this function. Can somebody satisfy my curiosity?

**Comment by chriskonnertz** [comment]
Hello.

Oh... well the solution of his riddle is that this is a Laravel function. I don’t know why it’s here.

**Comment by chriskonnertz** [comment]
Quick fix: https://github.com/chriskonnertz/open-graph/commit/8539c0f58dcae5bdd298eca660c9ec9e9a94e5cb

This is not a real fix but if the code did not work for you because of a missing function it should work now. 

=> https://github.com/chriskonnertz/open-graph/releases/tag/v1.0.7
