### ISSUE TITLE
Call to undefined method ChrisKonnertz\OpenGraph\OpenGraph::attributes()

### ISSUE THREAD

**Issue by bbdangar** [chriskonnertz/open-graph#30]

**Comment by KalanaPerera** [comment]
Same error, after the new update.

**Comment by KalanaPerera** [comment]
Have a look and please Approve or do a fix ASAP Thanks.

**Comment by chriskonnertz** [comment]
Hi,

thanks @KalanaPerera ! I will merge that soon.

**Comment by chriskonnertz** [comment]
Done. Thank you for contributing.

**Comment by KalanaPerera** [comment]
@chriskonnertz  did you update composer for this? Seems like not updated

**Comment by chriskonnertz** [comment]
@KalanaPerera I have created a new release (beta 2): https://github.com/chriskonnertz/open-graph/releases/tag/v2.0.0-beta2 You can reference this tag in your `composer.json` to include your bug fix.
