### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by Matlord93** [chriskonnertz/open-graph#37]
Bitte in der Datei composer.json folgende zeile 28 bearbeiten  "OpenGraph' => 'ChrisKonnertz\\OpenGraph\\OpenGraphFacade'" in "OpenGraph' => 'ChrisKonnertz\\OpenGraph\\OpenGraph".

Leider wird sonst dieses Modul von Laravel nicht direkt angesprochen und muss manuell bearbeitet werden.

**Comment by chriskonnertz** [comment]
Hi @Matlord93 , 

was ist der Grund für die Schließung?

**Comment by Matlord93** [comment]
Ich habe nicht mehr damit gerechnet, dass du hier nochmal prüftst ob es ein fehler gibt daher die schließung.
