### ISSUE TITLE
how to generate fb:app_id ?

### ISSUE THREAD

**Issue by leandroruel** [chriskonnertz/open-graph#4]
i'm looking for generate this tag <meta property="fb:app_id" content=""> but i don't know how.
![captura de tela de 2014-12-02 18 03 44](https://cloud.githubusercontent.com/assets/2836002/5269873/b8450c66-7a4d-11e4-96fd-1d32890d606a.png)

**Comment by chriskonnertz** [comment]
Solution for this problem incoming.

**Comment by chriskonnertz** [comment]
Solution:

    $og->tag('fb:app_id', '123', false);

Output:

    <meta property="fb:app_id" content="123" />

**Comment by leandroruel** [comment]
thanks
