### ISSUE TITLE
renderTags method should not be escaped in templates

### ISSUE THREAD

**Issue by otarza** [chriskonnertz/open-graph#7]
Hi, 

Documentation says that we should use renderTags() method inside template like this ``` {{ $og->renderTags() }} ``` which I believe is not correct, at least for Laravel 5.1. 

I'm new in Laravel, using 5.1 and I was able to render meta tags correctly only without escaping it like this:
```
{!! $og->renderTags() !!}
```
Maybe I'm wrong and missing something, if so let me know.

For now as I see It's just documentation problem, everything works well, thanks for this awesome package!

**Comment by chriskonnertz** [comment]
I have to take a more in-depth look at it - but yes, I assume you are right. The documentation needs a Laravel 5 update - urgently.

**Comment by chriskonnertz** [comment]
As you mentioned, in Laravel 5.x one has to use the `{!! ... !!}` tags. The `{{ ... }}` tags are old Laravel 4 style.

Updated the README: https://github.com/chriskonnertz/open-graph/commit/a540cce93a72362b709564c4a787640072014d21

Thanks for your feedback! These kind of issues are sometimes difficult to see for me. Let me now if there are any other unprecise / wrong statements in the README.
