### ISSUE TITLE
Generates og:article:XXX rather than article:XXX

### ISSUE THREAD

**Issue by oppiansteve** [chriskonnertz/open-graph#8]
...which therefore fails Facebook's validation (https://developers.facebook.com/tools/debug/og/object/).

and seemingly is against the spec - http://ogp.me/#type_article

Can you confirm that 'og:article:XXX' is definitely right?

Here's the relevant validation output:

Warnings That Should Be Fixed
Extraneous Property	Objects of this type do not allow properties named 'og:article:published_time'.
Extraneous Property	Objects of this type do not allow properties named 'og:article:modified_time'.
Parser Mismatched Metadata	The parser's result for this metadata did not match the input metadata. Likely, this was caused by the data being ordered in an unexpected way, multiple values being given for a property only expecting a single value, or property values for a given property being mismatched. Here are the input properties that were not seen in the parsed result: 'og:article:published_time, og:article:modified_time'

**Comment by chriskonnertz** [comment]
> Can you confirm that 'og:article:XXX' is definitely right?
Unfortunately I can not. I need to do more research but your concern might be legitimate.

**Comment by chriskonnertz** [comment]
Refactored a lot, added a tag class, tags can now decided if they want prexifing of 'og:' or not. 
Created a new branch because I think this needs more testing etc.

Commit: https://github.com/chriskonnertz/open-graph/commit/a0b82c3cd7cf3c44bf56cf2adf7f2f8607fa2f40

**Comment by chriskonnertz** [comment]
Merged the dev branch since I am not aware of any problems.
