### ISSUE TITLE
Could change to support Carbon dates too

### ISSUE THREAD

**Issue by oppiansteve** [chriskonnertz/open-graph#9]
You could change the `$date instanceof DateTime` to `is_a($date, 'DateTime')` to allow Carbon (https://github.com/briannesbitt/Carbon) dates too.

**Comment by chriskonnertz** [comment]
Hello,

thank you for your reasonable suggestion. Done. https://github.com/chriskonnertz/open-graph/commit/a95141312f31788fca13d038bcaa2723a7f4efb0
